version: '3.5'

services:
    php:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        volumes:
            - ./:/srv
        environment:
            - COMPOSER_HOME=/srv/.cache/composer
        restart: "no"
